name: CLI Version

on:
  schedule:
    # Run every Monday at 9am UTC
    - cron: "0 9 * * 1"
  workflow_dispatch:

jobs:
  check-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Get current documented version
        id: current
        run: |
          # Extract version from cli.md
          VERSION=$(grep -oP 'lychee/\K[0-9.]+' src/content/docs/guides/cli.md | head -1)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Get latest lychee version
        id: latest
        run: |
          VERSION=$(curl -s https://api.github.com/repos/lycheeverse/lychee/releases/latest | jq -r '.tag_name' | grep -oP '[0-9]+\.[0-9]+\.[0-9]+')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Compare versions
        id: compare
        run: |
          if [ "${{ steps.current.outputs.version }}" != "${{ steps.latest.outputs.version }}" ]; then
            echo "outdated=true" >> $GITHUB_OUTPUT
          else
            echo "outdated=false" >> $GITHUB_OUTPUT
          fi

      - name: Create or update issue
        if: steps.compare.outputs.outdated == 'true'
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Check if an issue already exists
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: 'documentation'
            });

            const existingIssue = issues.data.find(issue =>
              issue.title.includes('Update CLI documentation for lychee')
            );

            if (existingIssue) {
              // Add a comment to existing issue
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: existingIssue.number,
                body: `🔔 Reminder: Version mismatch still detected.\n\nCurrent: \`${{ steps.current.outputs.version }}\`\nLatest: \`${{ steps.latest.outputs.version }}\``
              });
            } else {
              // Create new issue (will be created by github-actions[bot])
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: `Update CLI documentation for lychee ${{ steps.latest.outputs.version }}`,
                body: `The CLI documentation may be outdated.\n\nCurrent: \`${{ steps.current.outputs.version }}\`\nLatest: \`${{ steps.latest.outputs.version }}\`\n\nRun \`lychee --help\` and update \`src/content/docs/guides/cli.md\` accordingly.`,
                labels: ['documentation']
              });
            }
